from enum import Enum

class MimeTypes(str, Enum):
    """Common MIME types used in the application"""
    # Image types
    PNG = "image/png"
    JPEG = "image/jpeg"
    GIF = "image/gif"
    SVG = "image/svg+xml"
    ICO = "image/vnd.microsoft.icon"
    BMP = "image/bmp"
    TIFF = "image/tiff"
    WEBP = "image/webp"
    AVIF = "image/avif"
    APNG = "image/apng"

    # Video types
    WEBM = "video/webm"
    MP4 = "video/mp4"
    OGG = "video/ogg"
    AVI = "video/x-msvideo"
    MPEG = "video/mpeg"
    THREE_GP = "video/3gpp"
    THREE_G2 = "video/3gpp2"
    MP2T = "video/mp2t"

    # Audio types
    AAC = "audio/aac"
    MIDI = "audio/midi"
    MP3 = "audio/mpeg"
    OGA = "audio/ogg"
    OPUS = "audio/ogg"
    WAV = "audio/wav"
    WEBA = "audio/webm"
    THREE_GP_AUDIO = "audio/3gpp"
    THREE_G2_AUDIO = "audio/3gpp2"

    # Document types
    PDF = "application/pdf"
    DOC = "application/msword"
    DOCX = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    XLS = "application/vnd.ms-excel"
    XLSX = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    PPT = "application/vnd.ms-powerpoint"
    PPTX = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    RTF = "application/rtf"
    TXT = "text/plain"
    CSV = "text/csv"
    HTML = "text/html"
    CSS = "text/css"
    JS = "text/javascript"
    JSON = "application/json"
    JSONLD = "application/ld+json"
    XML = "application/xml"
    XHTML = "application/xhtml+xml"
    XUL = "application/vnd.mozilla.xul+xml"
    ABW = "application/x-abiword"
    EPUB = "application/epub+zip"
    AZW = "application/vnd.amazon.ebook"
    ODP = "application/vnd.oasis.opendocument.presentation"
    ODS = "application/vnd.oasis.opendocument.spreadsheet"
    ODT = "application/vnd.oasis.opendocument.text"
    VSD = "application/vnd.visio"
    MPKG = "application/vnd.apple.installer+xml"
    ICS = "text/calendar"

    # Archive types
    ZIP = "application/zip"
    RAR = "application/vnd.rar"
    SEVEN_Z = "application/x-7z-compressed"
    TAR = "application/x-tar"
    GZIP = "application/gzip"
    BZIP = "application/x-bzip"
    BZIP2 = "application/x-bzip2"
    ARC = "application/x-freearc"
    JAR = "application/java-archive"

    # Font types
    TTF = "font/ttf"
    OTF = "font/otf"
    WOFF = "font/woff"
    WOFF2 = "font/woff2"
    EOT = "application/vnd.ms-fontobject"

    # Other types
    BIN = "application/octet-stream"
    CDA = "application/x-cdf"
    CSH = "application/x-csh"
    SH = "application/x-sh"
    PHP = "application/x-httpd-php"
    MJS = "text/javascript"
