name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - SCRUM-249-Deploy-containers-workflow
    tags:
      - 'v*'

env:
  IMAGE_NAME: core

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define Docker tags
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION_TAG=${GITHUB_REF#refs/tags/}
            echo "tag1=$VERSION_TAG" >> $GITHUB_OUTPUT
            echo "tag2=latest" >> $GITHUB_OUTPUT
          else
            UNSTABLE_TAG=unstable-$(date +'%y%V%u')
            echo "tag1=$UNSTABLE_TAG" >> $GITHUB_OUTPUT
          fi
      
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner,,}}/${IMAGE_NAME,,}:${{ steps.vars.outputs.tag1 }} .
    
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner,,}}/${IMAGE_NAME,,}:${{ steps.vars.outputs.tag1 }}
    
      - name: Tag and push 'latest' (if release)
        if: steps.vars.outputs.tag2 != ''
        run: |
          docker tag ghcr.io/${{ github.repository_owner,,}}/${IMAGE_NAME,,}:${{ steps.vars.outputs.tag1 }} ghcr.io/${{ github.repository_owner,,}}/${IMAGE_NAME,,}:${{ steps.vars.outputs.tag2 }}
          docker push ghcr.io/${{ github.repository_owner,,}}/${IMAGE_NAME,,}:${{ steps.vars.outputs.tag2 }}
      